name: virel
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py39h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39h06a4308_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.1=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.1=py39h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - ipykernel=6.4.1=py39h06a4308_1
  - ipython=7.27.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.4=pyhd3eb1b0_0
  - jedi=0.18.0=py39h06a4308_1
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39h06a4308_7
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - markupsafe=2.0.1=py39h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.3=py39h06a4308_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pyrsistent=0.18.0=py39h7f8727e_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.9.4=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - tzdata=2021a=h5d7bf9c_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py39h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.14.1
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - anyio==3.3.4
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - babel==2.9.1
    - bidict==0.21.3
    - cachetools==4.2.4
    - chardet==4.0.0
    - charset-normalizer==2.0.6
    - clang==5.0
    - click==8.0.1
    - cloudpickle==1.2.2
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.24
    - dnspython==2.1.0
    - docker-pycreds==0.4.0
    - easydict==1.9
    - einops==0.3.2
    - eventlet==0.32.0
    - flask==2.0.2
    - flask-socketio==5.1.1
    - flask-wtf==0.15.1
    - flatbuffers==1.12
    - fsspec==2021.10.0
    - future==0.18.2
    - gast==0.4.0
    - gitdb==4.0.7
    - gitpython==3.1.24
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - greenlet==1.1.2
    - grpcio==1.41.0
    - gunicorn==20.1.0
    - gym==0.15.7
    - h5py==3.1.0
    - idna==3.2
    - imageio==2.9.0
    - ipdb==0.13.9
    - isodate==0.6.0
    - itsdangerous==2.0.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - json5==0.9.6
    - jsonpatch==1.32
    - jsonpointer==2.1
    - jupyter-server==1.11.2
    - jupyterlab==3.2.4
    - jupyterlab-server==2.8.2
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - kornia==0.5.11
    - llvmlite==0.37.0
    - markdown==3.3.4
    - matplotlib==3.4.3
    - multidict==5.2.0
    - multiobject==0.0.3
    - multiset==2.1.1
    - munch==2.5.0
    - nbclassic==0.3.4
    - networkx==2.6.3
    - numba==0.54.1
    - numpy==1.19.5
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pandas==1.3.3
    - pathtools==0.1.2
    - pillow==8.3.2
    - pip==22.0.3
    - promise==2.3
    - protobuf==3.18.1
    - pstar==0.1.9
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.1.9
    - pycocotools==2.0.2
    - pydeprecate==0.3.1
    - pyglet==1.5.0
    - pyjson5==1.5.2
    - python-engineio==4.2.1
    - python-socketio==5.4.0
    - pytorch-lightning==1.4.9
    - pytz==2021.3
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - qj==0.2.0
    - rdflib==6.0.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.0
    - scipy==1.7.1
    - sentry-sdk==1.4.3
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==4.0.0
    - sniffio==1.2.0
    - subprocess32==3.5.4
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - timm==0.4.12
    - toml==0.10.2
    - torch==1.9.1+cu111
    - torch-geometric==2.0.1
    - torch-scatter==2.0.8
    - torch-sparse==0.6.12
    - torchaudio==0.9.1
    - torchfile==0.1.0
    - torchmetrics==0.5.1
    - torchsummary==1.5.1
    - torchvision==0.10.1+cu111
    - tqdm==4.62.3
    - tsne-torch==1.0.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - vapory==0.1.2
    - visdom==0.1.8.9
    - wandb==0.12.4
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - wtforms==2.3.3
    - yacs==0.1.8
    - yarl==1.7.0
    - yaspin==2.1.0
