alpha_entr: 0
assert_max_count: false
base_log: /dfs/user/dzeng/results/relation_analogy_new
canvas_size: 16
checkpoint_step: best
cl_weight: 1
classify: true
compute_mcs: false
ddp: false
edge_att_weight: 0
edge_rep_weight: 0
encoder_act: leakyrelu
evaluate: true
fine_tune: false
force_overwrite: true
force_py_backup: false
freeze_gin: false
gin_act: leakyrelu0.2
gin_last_act: false
gin_layers: 2
gin_mlp_layers: 3
in_channels: 9
inner_lr: 0.5
inter_weight: 1
intra_weight: 1
is_inner_loop: false
is_ixz: true
is_lookup_mask: false
ixz_gin_mean: true
ixz_weight: 0.1
learning_rate: 0.0001
load_latest: true
log_dir: null
lr_scheduler_type: None
max_count: 235
max_n_distractors: 0
min_n_distractors: 0
mlp_act: leakyrelu
mlp_act_gnn: leakyrelu0.2
mlp_concat: true
momentum: 0.9
multi_head_rel: false
n_examples: 2400
num_augs: 2
num_epochs: 18000
num_inner_loop: 5
num_objs: 3
num_rels: 3
obj_dim: 100
padding_objs: 3
pkl_name: data_rec.p
print_interval: 20
print_interval2: 10
print_interval3: 25
random_seed: 0
rel_dim: 20
rel_dim_m: 20
reparam_mode: diag
run_id: gin-MLP_16x16_classify_noalp_no-gin_last_act-3obj0dist
save_interval: 25
show_tsne: false
show_tsne_task: false
softmax_rel: false
supervised: false
task_batch_size: 168
total_tasks: 6
total_tr_examples: 8460
train_aug: true
train_data_shuffle: true
train_drop_last: true
train_mask_shuffle: true
weight_decay: 0
workers: 11
write_tb_imgs: false
